PesonalShopSolution/Areas/Admin/Models/Brand.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace PesonalShopSolution.Areas.Admin.Models
{
    public partial class Brand
    {

        public int IdBrand { get; set; }
        public string BrandName { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }
}

PesonalShopSolution/Models/Brand.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace PesonalShopSolution.Models
{
    public partial class Brand
    {

        public int IdBrand { get; set; }
        public string BrandName { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }
}

PesonalShopSolution/Areas/Admin/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PesonalShopSolution.Areas.Admin.Data;
using PesonalShopSolution.Areas.Admin.Models;

namespace PesonalShopSolution.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BrandsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BrandsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Brands
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brand.ToListAsync());
        }

        // GET: Admin/Brands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand
                .FirstOrDefaultAsync(m => m.IdBrand == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Admin/Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdBrand,BrandName")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Admin/Brands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // POST: Admin/Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdBrand,BrandName")] Brand brand)
        {
            if (id != brand.IdBrand)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.IdBrand))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Admin/Brands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand
                .FirstOrDefaultAsync(m => m.IdBrand == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Admin/Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand = await _context.Brand.FindAsync(id);
            _context.Brand.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(int id)
        {
            return _context.Brand.Any(e => e.IdBrand == id);
        }
    }
}

PesonalShopSolution/Areas/Admin/Views/Brands/Create.cshtml
@model PesonalShopSolution.Areas.Admin.Models.Brand

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">Create Brands</h4>
                    </div>
                    <p></p>
                    <div class="card-body">
                        <form asp-action="Create" asp-controller="Brands">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="BrandName" class="bmd-label-floating"><b>Brand_Name :</b></label>
                                        <input asp-for="BrandName" type="text" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <center>
                                <button type="submit" class="btn btn-primary ">Create Brands</button>
                            </center>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

PesonalShopSolution/Areas/Admin/Views/Brands/Delete.cshtml
@model PesonalShopSolution.Areas.Admin.Models.Brand

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">Delete Brands</h4>
                    </div>
                    <p></p>
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.BrandName) :
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.BrandName)
                            </dd>
                        </dl>

                        <form asp-action="Delete">
                            <input type="hidden" asp-for="IdBrand" />
                            <input type="submit" value="Delete" class="btn btn-danger" /> |
                            <a asp-action="Index">Back to List</a>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

PesonalShopSolution/Areas/Admin/Views/Brands/Edit.cshtml
@model PesonalShopSolution.Areas.Admin.Models.Brand

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">Edit Brands</h4>
                    </div>
                    <p></p>
                    <div class="card-body">
                        <form asp-action="Edit" asp-controller="Brands">
                            <div class="row">
                                <input asp-for="IdBrand" type="hidden" class="form-control">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="BrandName" class="bmd-label-floating"><b>Brand_Name :</b></label>
                                        <input asp-for="BrandName" type="text" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <center>
                                 <button type="submit" class="btn btn-primary ">Edit Brands</button>
                            </center>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

PesonalShopSolution/Areas/Admin/Views/Brands/Index.cshtml
@model IEnumerable<PesonalShopSolution.Areas.Admin.Models.Brand>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a asp-action="Create" ><i class="fa fa-plus-circle" aria-hidden="true" style="font-size:30px"> Create </i></a>
                </p>
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">Brands Table</h4>
                     
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                <th>
                                    ID
                                </th>
                                <th>
                                    BrandsName
                                </th>
                                <th>Edit</th>
                                <th>Delete</th>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IdBrand)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.BrandName)
                                        </td>
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.IdBrand"><i class="fa fa-pencil-square-o" style="font-size:20px" aria-hidden="true"></i></a>
                                        </td>
                                        <td>
                                            <a asp-action="Delete" asp-route-id="@item.IdBrand"><i class="fa fa-trash" style="font-size:20px" aria-hidden="true"></i></a>
                                        </td>
                                       
                                    </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>