PesonalShopSolution/Areas/Admin/Models/Specification.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace PesonalShopSolution.Areas.Admin.Models
{
    public partial class Specification
    {
        public int IdSpecifications { get; set; }

        public int? IdProduct { get; set; }
        public string Shape { get; set; }
        public string Gender { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
        public string Weight { get; set; }
        public string Warranty { get; set; }

        public virtual ICollection<Product> Product { get; set; }
        public virtual Product IdProducts { get; set; }
    }
}

PesonalShopSolution/Models/Specification.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace PesonalShopSolution.Models
{
    public partial class Specification
    {
        public int IdSpecifications { get; set; }
        public int? IdBrand { get; set; }
        public string Shape { get; set; }
        public string Gender { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
        public string Weight { get; set; }
        public string Warranty { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }
}

PesonalShopSolution/Areas/Admin/Controllers/SpecificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PesonalShopSolution.Areas.Admin.Data;
using PesonalShopSolution.Areas.Admin.Models;

namespace PesonalShopSolution.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SpecificationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SpecificationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Specifications
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Specification.Include(s => s.IdProducts);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Admin/Specifications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specification = await _context.Specification
                .Include(s => s.IdProducts)
                .FirstOrDefaultAsync(m => m.IdSpecifications == id);
            if (specification == null)
            {
                return NotFound();
            }
            ViewBag.specifications = _context.Product.ToList();
            return View(specification);
        }

        // GET: Admin/Specifications/Create
        public IActionResult Create()
        {
            ViewBag.specifications = _context.Product.ToList();
            return View();
        }

        // POST: Admin/Specifications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdSpecifications,IdProduct,Shape,Gender,Color,Material,Weight,Warranty")] Specification specification)
        {
            if (ModelState.IsValid)
            {
                _context.Add(specification);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.specifications = _context.Product.ToList();
            return View(specification);
        }

        // GET: Admin/Specifications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specification = await _context.Specification.FindAsync(id);
            if (specification == null)
            {
                return NotFound();
            }
            ViewBag.specifications = _context.Product.ToList();
            return View(specification);
        }

        // POST: Admin/Specifications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdSpecifications,IdProduct,Shape,Gender,Color,Material,Weight,Warranty")] Specification specification)
        {
            if (id != specification.IdSpecifications)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(specification);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpecificationExists(specification.IdSpecifications))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProduct"] = new SelectList(_context.Product, "Id", "Id", specification.IdProduct);
            return View(specification);
        }

        // GET: Admin/Specifications/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specification = await _context.Specification
                .Include(s => s.IdProducts)
                .FirstOrDefaultAsync(m => m.IdSpecifications == id);
            if (specification == null)
            {
                return NotFound();
            }

            return View(specification);
        }

        // POST: Admin/Specifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var specification = await _context.Specification.FindAsync(id);
            _context.Specification.Remove(specification);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpecificationExists(int id)
        {
            return _context.Specification.Any(e => e.IdSpecifications == id);
        }
    }
}

PesonalShopSolution/Areas/Admin/Views/Specifications/Create.cshtml
@model PesonalShopSolution.Areas.Admin.Models.Specification

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<!-- End Navbar -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a asp-action="Index"><i class="fa fa-arrow-left" aria-hidden="true" style="font-size:30px"> Back </i></a>
                </p>
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">Create Specification </h4>
                    </div>
                    <div class="card-body">
                        <form asp-action="Create" asp-controller="Specifications">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="IdProduct" class="bmd-label-floating"><b>Product_Name :</b></label>
                                        <select asp-for="IdProduct" class="form-control" asp-items="@(new SelectList(ViewBag.specifications,"Id","ProductName"))"></select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Shape" class="bmd-label-floating"><b>Shape :</b></label>
                                        <input asp-for="Shape" type="text" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Gender" class="bmd-label-floating"><b>Gender :</b></label>
                                        <select asp-for="Gender" class="form-control">
                                            <option value="Male">Male</option>
                                            <option value="Male">Female</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Color" class="bmd-label-floating"><b>Color :</b></label>
                                        <input asp-for="Color" type="text" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Material" class="bmd-label-floating"><b>Material :</b></label>
                                        <input asp-for="Material" type="text" class="form-control" required>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Weight" class="bmd-label-floating"><b>Weight :</b></label>
                                        <input asp-for="Weight" type="text" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Warranty" class="bmd-label-floating"><b>Warranty :</b></label>
                                        <input asp-for="Warranty" type="text" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <center>
                                <button type="submit" class="btn btn-primary ">Create Specification</button>
                            </center>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

PesonalShopSolution/Areas/Admin/Views/Specifications/Delete.cshtml
@model PesonalShopSolution.Areas.Admin.Models.Specification

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">Delete Specification </h4>
                    </div>
                    <p></p>
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Shape)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Shape)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Gender)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Gender)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Color)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Color)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Material)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Material)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Weight)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Weight)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Warranty)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Warranty)
                            </dd>
                            <dt class="col-sm-2">
                                ProductName
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.IdProducts.ProductName)
                            </dd>
                        </dl>

                        <form asp-action="Delete">
                            <input type="hidden" asp-for="IdSpecifications" />
                            <input type="submit" value="Delete" class="btn btn-danger" /> |
                            <a asp-action="Index">Back to List</a>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

PesonalShopSolution/Areas/Admin/Views/Specifications/Details.cshtml
@model PesonalShopSolution.Areas.Admin.Models.Specification

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!-- End Navbar -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a asp-action="Index"><i class="fa fa-arrow-left" aria-hidden="true" style="font-size:30px"> Back </i></a>
                </p>
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">Detail Specification </h4>
                    </div>
                    <div class="card-body">
                        
                            <div class="row">
                                <input asp-for="IdSpecifications" type="hidden" class="form-control" required>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="IdProduct" class="bmd-label-floating"><b>Product_Name :</b></label>
                                        <select asp-for="IdProduct" class="form-control" asp-items="@(new SelectList(ViewBag.specifications,"Id","ProductName"))"></select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Shape" class="bmd-label-floating"><b>Shape :</b></label>
                                        <input asp-for="Shape" type="text" class="form-control" readonly>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Gender" class="bmd-label-floating"><b>Gender :</b></label>
                                        <input asp-for="Gender" type="text" class="form-control" readonly>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Color" class="bmd-label-floating"><b>Color :</b></label>
                                        <input asp-for="Color" type="text" class="form-control" readonly>
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Material" class="bmd-label-floating"><b>Material :</b></label>
                                        <input asp-for="Material" type="text" class="form-control" readonly>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Weight" class="bmd-label-floating"><b>Weight :</b></label>
                                        <input asp-for="Weight" type="text" class="form-control" readonly>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Warranty" class="bmd-label-floating"><b>Warranty :</b></label>
                                        <input asp-for="Warranty" type="text" class="form-control" readonly>
                                    </div>
                                </div>
                            </div>
                           
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

PesonalShopSolution/Areas/Admin/Views/Specifications/Edit.cshtml
@model PesonalShopSolution.Areas.Admin.Models.Specification

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<!-- End Navbar -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a asp-action="Index"><i class="fa fa-arrow-left" aria-hidden="true" style="font-size:30px"> Back </i></a>
                </p>
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">Edit Specification </h4>
                    </div>
                    <div class="card-body">
                        <form asp-action="Edit" asp-controller="Specifications">
                            <div class="row">
                                <input asp-for="IdSpecifications" type="hidden" class="form-control" required>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="IdProduct" class="bmd-label-floating"><b>Product_Name :</b></label>
                                        <select asp-for="IdProduct" class="form-control" asp-items="@(new SelectList(ViewBag.specifications,"Id","ProductName"))"></select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Shape" class="bmd-label-floating"><b>Shape :</b></label>
                                        <input asp-for="Shape" type="text" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Gender" class="bmd-label-floating"><b>Gender :</b></label>
                                        <select asp-for="Gender" class="form-control">
                                            <option value="Male">Male</option>
                                            <option value="Female">Female</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Color" class="bmd-label-floating"><b>Color :</b></label>
                                        <input asp-for="Color" type="text" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Material" class="bmd-label-floating"><b>Material :</b></label>
                                        <input asp-for="Material" type="text" class="form-control" required>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Weight" class="bmd-label-floating"><b>Weight :</b></label>
                                        <input asp-for="Weight" type="text" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label asp-for="Warranty" class="bmd-label-floating"><b>Warranty :</b></label>
                                        <input asp-for="Warranty" type="text" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <center>
                                <button type="submit" class="btn btn-primary ">Edit Specification</button>
                            </center>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

PesonalShopSolution/Areas/Admin/Views/Specifications/Index.cshtml
@model IEnumerable<PesonalShopSolution.Areas.Admin.Models.Specification>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a asp-action="Create"><i class="fa fa-plus-circle" aria-hidden="true" style="font-size:30px"> Create </i></a>
                </p>
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">Specifications Table</h4>

                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                <th>ID</th>
                                <th>Product Name</th>
                                <th>Shape</th>
                                <th>Gender</th>
                                <th>Color</th>
                                <th>Material</th>
                                <th>Weight</th>
                                <th>Warranty</th>
                                <th>Edit</th>
                                <th>Detail</th>
                                <th>Delete</th>
                                <th>Origin</th>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IdSpecifications)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IdProducts.ProductName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Shape)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.Gender)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Color)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Material)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Weight)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Warranty)
                                        </td>

                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.IdSpecifications"><i class="fa fa-pencil-square-o" style="font-size:20px" aria-hidden="true"></i></a>
                                        </td>
                                        <td>
                                            <a asp-action="Details" asp-route-id="@item.IdSpecifications"><i class="fa fa-eye" style="font-size:20px" aria-hidden="true"></i></a>
                                        </td>
                                        <td>
                                            <a asp-action="Delete" asp-route-id="@item.IdSpecifications"><i class="fa fa-trash" style="font-size:20px" aria-hidden="true"></i></a>
                                        </td>
                                        <td>
                                            <a asp-action="Details" asp-route-id="@item.IdProduct" asp-controller="Products"><i class="fa fa-cube" style="font-size:20px" aria-hidden="true"></i></a>
                                        </td>
                                    </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>